### ISSUE TITLE
Feature Flags talk ConFoo 2024

### ISSUE THREAD

**Issue by doum-vigeant-nventive** [carboneater/confoo-2024-mutation-testing#1]
Hello, I saw your talk yesterday at ConFoo on feature flags and noted down the repo but it doesn't seem to be available, would you mind making it public? :)

**Comment by carboneater** [comment]
Hey,
Thanks for attending!

I uploaded the rendered slides, and expanded the readme, so you can play with the demo, get a quick primer or run the slides using Sli.Dev.

I read the repo in private mode, without logging in, looked public to me.

Is it working for you now?

**Comment by doum-vigeant-nventive** [comment]
Hmmm I still don't see it. Just to be sure, this is the correct link?
https://github.com/carboneater/confoo-2024-feature-flags

**Comment by carboneater** [comment]
Oh, I got confused.
You're very right, that talk is private!
I'll fix it right away!

**Comment by carboneater** [comment]
Ok, it's now public
Apologies for the delay, the Pulumi talk was that one talk that just justified my boss paying my confoo ticket!
